### ISSUE TITLE
Cover components with unit tests

### ISSUE THREAD

**Issue by TejasQ** [contiamo/restful-react#1]
# Why
Unit tests are good and allow us to have predictable software.

# What
Currently, components like [Get](https://github.com/contiamo/restful-react/blob/master/src/index.tsx) and [Poll](https://github.com/contiamo/restful-react/blob/master/src/Poll.tsx) work reliably and beautifully, but are not covered with unit tests. It would be nice if we had them covered with test in order to prevent side effects and surprises when consuming these components.

**Comment by Xiot** [comment]
I can take this on!

**Comment by TejasQ** [comment]
Do it! 💪

**Comment by TejasQ** [comment]
@Xiot, still interested to finish this?

**Comment by Xiot** [comment]
Sorry, I haven't had any time recently.

**Comment by TejasQ** [comment]
Would you still like to do it?
