### ISSUE TITLE
Add `displayName` for Context component

### ISSUE THREAD

**Issue by stereobooster** [contiamo/restful-react#107]
**Is your feature request related to a problem? Please describe.**

Add `displayName` for Context component to improve DX

```tsx
SomeContext.Consumer.displayName = "SomeContext.Consumer";
SomeContext.Provider.displayName = "SomeContext.Provider";
```

**Describe the solution you'd like**

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by TejasQ** [comment]
Let's do it! Great for community participation!

**Comment by alfdocimo** [comment]
Hi! I just found out about this awesome library and would very much like to help out! is this enhancement already planned? If not, I'd like to contribute with this if that's okay 😊

**Comment by TejasQ** [comment]
DO IT! Welcome to the project! Let's play! ❤️

**Comment by alfdocimo** [comment]
Hi again! Created a PR for this (: in -> #166

**Comment by TejasQ** [comment]
Awesome! @stereobooster will take a look at it and get back to you!

**Comment by South-Paw** [comment]
@stereobooster @fabien0102 @TejasQ looks like this is also merged so issue could be closed 👍

**Comment by TejasQ** [comment]
Thanks!
