### ISSUE TITLE
Fix useGet path composition

### ISSUE THREAD

**Issue by TejasQ** [contiamo/restful-react#111]
Opening this because of [private Contiamo repo PR that the outside world can't see that references this problem](https://github.com/contiamo/pantheon-ui/pull/343/files/c7fe9b35cf9faaf476d5e4aa76ca2cabceeb16c0..31c81acb73ed7da39fe8a87a0360bc9ae65dca43#diff-3c7e96d0ee3dae738e91adf35be62fdbR49), so we don't forget about it.

**Comment by fabien0102** [comment]
closed by #114
