### ISSUE TITLE
Poll doesn't support function for requestOptions same way as Get does

### ISSUE THREAD

**Issue by vxsx** [contiamo/restful-react#112]
**Describe the bug**
Poll doesn't support function for requestOptions same way as Get does

**To Reproduce**
1. Create a RestfulProvider with requestOptions as a function returning some header
2. Use Get and Poll inside
3. Open devtools and see that headers on poll requests are not sent

**Expected behavior**
Behaviour should be the same for Poll and Get

**Additional context**
I found this issue while using a version of safari that requred `credentials: 'same-origin'` in request options and it took me a while to figure out

**Comment by vxsx** [comment]
Yes, this is something I would like to do at some point this week

**Comment by TejasQ** [comment]
Nice! Excited to see how you go!
