### ISSUE TITLE
Implement multipart/form-data handling when generating the component from OpenAPI spec

### ISSUE THREAD

**Issue by mpotomin** [contiamo/restful-react#119]
**Is your feature request related to a problem? Please describe.**
For the post request, it would be amazing 😍 to have autogeneration to handle `multipart/form-data` section of the OpenAPI spec, to make it make it possible to generate React components also for uploading a form data. 

**Additional context**
Example of the OpenaAPI spec:

```yaml
  "/api/upload":
    post:
      tags:
        - table
        - file
      summary: Upload a file
      description: Upload a file 
      operationId: UploadFile
      parameters:
        - name: collectionId
          in: path
          description: UUID or name of the collection
          required: true
          schema:
            type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
        description: File data
        required: true

```

**Comment by TejasQ** [comment]
I agree. This would be a great way to onboard people into the project. Let's leave it for the community if it's non-blocking?

**Comment by TejasQ** [comment]
Closing in favor of https://github.com/contiamo/restful-react/issues/168
