### ISSUE TITLE
Handle request concurrency

### ISSUE THREAD

**Issue by TejasQ** [contiamo/restful-react#12]
From the comment in #11 ([specifically this](https://github.com/contiamo/restful-react/pull/11#discussion_r202736853)), we ought to come up with a way of handling multiple requests made in rapid succession.

**Comment by fabien0102** [comment]
Even if it's not perfect yet, we can use the `debounce` prop to deal with this issue for now ;)

**Comment by TejasQ** [comment]
We also handle this nicely in `Poll`, right?

**Comment by TejasQ** [comment]
We also handle this nicely in `Poll`, right? @fabien0102

**Comment by fabien0102** [comment]
Not yet, if you change the `path` props, nothing cancel the current request (I have deal with cancelling request on component unmount only for now ;) )

**Comment by stereobooster** [comment]
With hooks we can handle it https://github.com/contiamo/restful-react/issues/101

**Comment by TejasQ** [comment]
Closing because we cancel requests.
