### ISSUE TITLE
Promise callback of Mutate function not being called

### ISSUE THREAD

**Issue by AJHenry** [contiamo/restful-react#121]
**Describe the bug**
When using a `Mutate` function with the PUT verb, the callback of the mutation promise is not called

**To Reproduce**
Minimal Code example to reproduce
```js
<Mutate
    verb="PUT"
    base={`https://jsonplaceholder.typicode.com/put/posts/1`}
>
    {(update, { loading, error }) => {
    console.log(loading);
    console.log(error);
    return (
        <div
        style={{ width: "100px", height: "100px" }}
        onClick={() => {
            console.log("Clicked");
            update({
            id: 1,
            title: "foo",
            body: "bar",
            userId: 1
            }).then(() => console.log("Then called"));
        }}
        >
        Click
        </div>
    );
    }}
</Mutate>
```

There are no throw errors and loading turns from false -> true -> false indicating an operation took place. 

Not sure if the operation is being aborted early for some reason, or is throwing an error that is not being caught by the Mutate function.

_NOTE_: You can use the `.finally` method on the promise but it is unclear if this is intended behavior in the docs

**Expected behavior**
According to the docs, "Each mutation returns a promise...", which to me indicates that I should be allowed to use the `.then` function on the returned promise. 
 

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10 1803
 - Browser: Firefox 
 - Version: 66.0.5 (64-bit)

**Additional Note**
Even the docs are using the `.then` function on the mutate function so I believe this is definitely a bug
[See here](https://github.com/contiamo/restful-react#mutations-with-mutate)

```js
onClick={() => delete(movie.id).then(() => dispatch('DELETED'))}
```

Also a side note, `delete` is a reserved word in JS and that line will result in a compile error

**Comment by TejasQ** [comment]
Hey @ajhenry! Thanks for reporting this! It’s almost midnight in Germany. We will for sure look at this in the morning. 

Appreciate your using our tools!

**Comment by fabien0102** [comment]
Indeed the error is not correctly propagated in `Mutate` (https://github.com/contiamo/restful-react/blob/master/src/Mutate.tsx#L181), the trick is to add a `.catch` statement. In your snippet you just have a 404 error for example. I've spotted this bug yesterday during my `useMutate` implementation but you was quicker than me for reporting 😉 

https://codesandbox.io/embed/competent-lalande-z3jsk?fontsize=14

Good catch for the example in the documentation 😅 using `delete` is quite stupid ^^

**Comment by TejasQ** [comment]
Published v7.6.2 under `next`.

`npm install restful-react@next` should fix this for you now, @AJHenry. Please let us know if it works and we'll close the issue.

**Comment by AJHenry** [comment]
@TejasQ Yes I can confirm that this PR fixed the issue with the error callback.

One other thing I did notice is that when issuing a PUT verb, it is common to get back a 204 response code (No Content), but it seems the fetch response handler still tries to call `.json()` on it anyway, resulting in the data section of the returned result with this: `JSON.parse: unexpected end of data at line 1 column 1 of the JSON data`. 

This is more of a nitpick issue though, but thank you for the fix!

**Comment by TejasQ** [comment]
Woah. Thanks for that! We'll fix that too!

**Comment by fabien0102** [comment]
Time to add a new unit test! Thanks for the feedback 💯
