### ISSUE TITLE
Avoid Error Updates on Unmounted Component

### ISSUE THREAD

**Issue by AJHenry** [contiamo/restful-react#136]
**Describe the bug**
The `Get` component has an abort handler that will cancel any state updates after the component umounts. However, since the fetch call is wrapped in a try catch block, it will bypass the abort check and update state resulting in the classic `Warning: Can't perform a React state update on an unmounted component`

This is because the abort check is after the catch block intercepts the error thrown by `fetch`

https://github.com/contiamo/restful-react/blob/529bdb35c9c6baec36cd34ccd76510726b142332/src/Get.tsx#L256-L262

I was able to fix this issue by putting the abort check in the catch block as well

https://github.com/AJHenry/restful-react/blob/8627e00f58cfc8c69d050c0d9a811717aa6e0533/src/Get.tsx#L381-L385

**To Reproduce**
1. Mount the Get component
2. Call an API that will result in an error such as 401, 404, etc
3. Unmount the component before the call finishes and the error is thrown

**Expected behavior**
The state should not be updated when the component is unmounted, regardless of whether there is an error or not

**Additional context**
I would open a PR for this issue myself but I am unable to reliably reproduce the issue in a unit test (as `setState` on unmounted components are fairly hard to test)

**Comment by TejasQ** [comment]
Thanks for the issue, @AJHenry! I'd suggest opening a PR regardless and we can collaborate towards a good working test together. What do you think?

**Comment by AJHenry** [comment]
@TejasQ Sounds good, I can open a PR later today

**Comment by stereobooster** [comment]
@fabien0102 @AJHenry is this resolved issue? Can we close the ticket?

**Comment by AJHenry** [comment]
@stereobooster this should be fixed as #137 was merged in awhile back
