### ISSUE TITLE
useMutate can crash if the server is sending a bad JSON

### ISSUE THREAD

**Issue by fabien0102** [contiamo/restful-react#140]
**Describe the bug**
ngnix is a bad boy, you ask for a json, send you an html -> boom!

We already handle this case on classic component, apparently I forgot to port this edge case to the hook one 😕 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by TejasQ** [comment]
u ok

**Comment by fabien0102** [comment]
I'm fine, I'm trying to find a bug, I was suspecting in restful-react, but apparently it's cover… So I just add a unit test for the next time ;)
