### ISSUE TITLE
Better docs / examples

### ISSUE THREAD

**Issue by frank-borkin** [contiamo/restful-react#146]
Hi,

As someone somewhat new to React, this seems a good way to do simple REST requests - but there are a lot of gotchas, and the example snippets aren't enough to understand why things don't work as expected.
Example:

import Mutate from "restful-react";
<Mutate verb="POST" path="/location">
 {(addLocation) => (
<Button outline color="gr" onClick={() => addLocation()}> Add</Button>)}
</Mutate>

fails with "No function called addLocation()". You need to change the import to:
import { Mutate } from "restful-react";

This may be obvious to someone who knows React well, but to someone new it's really not.
Can the docs be updated, or (better) a working example complete mini-app be created?

Thanks

**Comment by TejasQ** [comment]
Hey @frank-borkin – absolutely! Would you like to create this? We're happy to help out where you need it!
