### ISSUE TITLE
Triple change of the state in the useGet

### ISSUE THREAD

**Issue by stereobooster** [contiamo/restful-react#149]
**Describe the bug**

There is a bug in restful-react, it sets state thrice after changing input values:
 - "not loading" with previous data
 - then "loading" state
 - then "not loading" with new data

**To Reproduce**

To be done

**Expected behavior**

I would expect change of the state twice:

 - "loading" state
 - then "not loading" with new data

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome
 - Version  Version 76.0.3809.100 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by TejasQ** [comment]
@fabien0102 please triage this.
