### ISSUE TITLE
Incorrect exit code on errors

### ISSUE THREAD

**Issue by LucasRoesler** [contiamo/restful-react#154]
**Describe the bug**
I am trying to use restful-rect as part of a CI flow to ensure that a OpenAPI spec will correctly generate a Typescript client, but even when restful-react fails, Jenkins treats the CI stage as a success.  In Jenkins it looks like this 

![image](https://user-images.githubusercontent.com/891889/66818905-5257b000-ef3e-11e9-960f-7ca4787e4b04.png)

**To Reproduce**
If you  have docker, you can run 
1. `docker run --rm -it node curl https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore.yaml --output api.yaml; npx restful-react@next import --file api.yaml --output ignoreme.tsx; echo $?`
2. See that that last line it prints is `0`

**Expected behavior**
I would expect the above command to print `1` or at least some other positive number 1--255, per https://www.tldp.org/LDP/abs/html/exitcodes.html#EXITCODESREF

**Screenshots**
![image](https://user-images.githubusercontent.com/891889/66819513-68b23b80-ef3f-11e9-9db6-670ca397b5cd.png)

**Additional context**
Add any other context about the problem here.  I used the docker container to reproduce this here because my use case in CI is very similar/the same as the docker run command

**Comment by TejasQ** [comment]
Thanks for this. Will fix.
