### ISSUE TITLE
Axios interceptors alternative

### ISSUE THREAD

**Issue by josvegit** [contiamo/restful-react#164]
Hi, this is such a cool lib, really props you to guys.

I have an API that needs to update its token after each successful apicall (great I know). I use axios interceptors for this today, I failed to find something similar from your documentation. Is there anyway to run some code before and after each request ?

Also, you guys use AbortController to cancel requests, do you need a polyfill for that to work in IE and similar shitty browsers ?

Again this is so cool.

**Comment by josvegit** [comment]
By looking at your code.

I guess you could emulate it with **requestOptions** before actually returning options and then in **resolve**, before resolving the data. But that feels like the wrong place for it :D

**Comment by josvegit** [comment]
Axios interceptors => https://github.com/axios/axios#interceptors

**Comment by TejasQ** [comment]
Hey @josvegit! Thank you for opening this issue! 

> I guess you could emulate it with requestOptions before actually returning options and then in resolve, before resolving the data. But that feels like the wrong place for it :D

Why does that feel like the wrong place for it? We think this actually makes sense. Are you able to meet your needs with this API?

**Comment by josvegit** [comment]
Yeah I think I can get it working with these functions, did not realize that you could define this on a global scale using **RestfulProvider** so I thought that I had to write this token-update code everywhere in my app, but nvm my bad.

**Comment by TejasQ** [comment]
Glad it works for you, @josvegit!
