### ISSUE TITLE
Cancel requests

### ISSUE THREAD

**Issue by josvegit** [contiamo/restful-react#165]
Again cool lib.

The logic for cancelling requests on unmount doesn't work, getting:

![image](https://user-images.githubusercontent.com/24354568/68071227-bcfb4f00-fd78-11e9-8c90-593ba0294b85.png)

In useGet:

![image](https://user-images.githubusercontent.com/24354568/68071250-f5029200-fd78-11e9-9f0e-9130f7110224.png)

**Comment by josvegit** [comment]
If you use the useGet in a component and quickly move away from it, you will get a:

![image](https://user-images.githubusercontent.com/24354568/68071227-bcfb4f00-fd78-11e9-8c90-593ba0294b85.png)

**Comment by josvegit** [comment]
Happens in useGet

![image](https://user-images.githubusercontent.com/24354568/68071250-f5029200-fd78-11e9-9f0e-9130f7110224.png)

**Comment by TejasQ** [comment]
Hey @josvegit! Thanks again for this! You're doing a great job contributing to our library. Are you able to provide a [CodeSandbox](https://codesandbox.io) reproduction of this issue? We're having some trouble reproducing it and will be able to fix it once we have a more reliable reproduction.

**Comment by josvegit** [comment]
Ill get you a sample project !

**Comment by TejasQ** [comment]
Thank you!

**Comment by josvegit** [comment]
https://codesandbox.io/s/flamboyant-paper-1oi7l

**Comment by josvegit** [comment]
click "Show LoaderComponent"

look in console

**Comment by josvegit** [comment]
you might have to try more then once depending on how fast the https://swapi.co/documentation#people api is

**Comment by TejasQ** [comment]
@josvegit great catch! Thank you for reporting this.

Question – can you confirm that the request is actually _not_ cancelled? I ask because it seems to cancel in our network tab: 

![image](https://user-images.githubusercontent.com/9947422/68136853-3be1ba80-ff26-11e9-97cc-dd46c6e67ea7.png)

What we're seeing is that we try to set state on an unmounted component, as reported, but the request does indeed cancel.

Can you confirm this?

**Comment by josvegit** [comment]
Yup, it does cancel the request!

**Comment by TejasQ** [comment]
No problem! You've given us a really good bone to chew on! Thank you! We'll have a fix shortly.

**Comment by ApacheEx** [comment]
FYI: I've checked sandbox with the latest version (14.2.1) and it's not actual anymore. So, I think this issue can be closed.
