### ISSUE TITLE
Support Class Components

### ISSUE THREAD

**Issue by joncursi** [contiamo/restful-react#167]
I would like to use this library within a class component. E.g., rather than `useGet` within a function component, utilizing `get` within a class method.

The class component is rather complex and not conducive to being broken down / written as a function component. Furthermore, I'm trying to use `componentDidUpdate` to trigger a re-fetch.

**Comment by TejasQ** [comment]
You can totally use it with class components already! The library exposes `<Get />`, which is behaviorally equivalent to `useGet`, but instead implements a render props API. Give it a try?

**Comment by TejasQ** [comment]
@joncursi does this resolve your issue?

**Comment by fabien0102** [comment]
As said by @TejasQ you can totally use `<Get />` and `<Mutate />` instead of the hook version 😉

**Comment by benmonro** [comment]
@TejasQ @fabien0102 how would this work in a componentDidMount for example?
