### ISSUE TITLE
Bug with sending FormData as request body

### ISSUE THREAD

**Issue by jakewtaylor** [contiamo/restful-react#168]
**Describe the bug**
Sending a multipart/form-data request with FormData as a body is not possible currently.

When you use FormData as a body, the `Content-Type` header should be set to `multipart/form-data; boundary=<BOUNDARY_NAME>`. The browser usually handles this itself - not specifying a `Content-Type` header causes the browser to apply one itself.

The problem is that `useMutate` is always guessing a `Content-Type` header, based on the request body - meaning the browser won't set the header, and thus the request is causing errors on our backend (`System.IO.InvalidDataException: Missing content-type boundary.`). I'm fairly certain this isn't unique to us, but it is a weird edge case.

As far as I can tell, there's no way you can specify the boundary name manually, so the only option would be to not set the `Content-Type` header when the request body is an instance of `FormData`.

**To Reproduce**
```tsx
const useFileUpload = () => {
  const { mutate, loading } = useMutate({
    path: '/file/upload/path',
    verb: 'POST',
  });

  return {
    loading,
    upload(file: File) {
      const formData = new FormData();
      formData.append('file', file);

      return mutate('', { body: formData });
    },
  };
}
```

On our C# API (I'm not entirely sure what our backend stack is), this request fails - because of the `Content-Type` header set in `useMutate`.

**Expected behavior**
If request body is an instance of FormData, no 'Content-Type' header should be set by restful-react, it should be left undefined so that the browser can handle it.

**Screenshots**
Example request payload:
![image](https://user-images.githubusercontent.com/8126758/68318111-27cbc380-00b4-11ea-934b-d303f42630b2.png)

The 'Content-Type' header, by default, is set to 'text/plain', overriding it manually with 'multipart/form-data' causes our API error because the boundary name has not been configured. It should be set to `multipart/form-data; boundary=<BOUNDARY_NAME>`

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome / Opera
 - Version: latest

**Comment by TejasQ** [comment]
This is a great catch! Would you like to open a PR that fixes it? Or shall we?

**Comment by jakewtaylor** [comment]
I wish I could but I don't have the time 😞 I hope I've provided enough info to make it an easy solution 😄

**Comment by TejasQ** [comment]
It definitely helps! Thanks a lot!

**Comment by dcruzin** [comment]
I think this is issue is not totally fixed. How can I push a branch with a fix? I'm getting 403 when trying to push
