### ISSUE TITLE
Case conversion support

### ISSUE THREAD

**Issue by qw-in** [contiamo/restful-react#170]
**Is your feature request related to a problem? Please describe.**
One of my favourite features in most graphql client and server implementations is the ability to automatically convert between cases. For example in the `fieldNameNormalizer` in `apollo-link-rest`. Wondering if there is any interest in adding support to `restful-react`

**Describe the solution you'd like**
1. Runtime data transformations - could potentially be as simple as passing a `reviver` to `JSON.parse` that transforms keys
1. Code generation transform - change types etc to match case conversion

**Comment by TejasQ** [comment]
Hey, @qw-in! Welcome to the project! We're happy you're here! I believe we have the capacity to fulfill number 2 on your list:

> Code generation transform - change types etc to match case conversion

We have [support for transformers](https://github.com/contiamo/restful-react#transforming-an-original-spec) for the generated code. Would that meet your use case?

**Comment by TejasQ** [comment]
@qw-in?

**Comment by qw-in** [comment]
@TejasQ 

I think the transformers are what I was looking for, thanks!

As for number 1 I can probably do it outside the library, will close
