### ISSUE TITLE
Support request/response interceptors

### ISSUE THREAD

**Issue by schneck** [contiamo/restful-react#171]
Hi there,

thanks for this libary, looks really nice. I have a use case however I'm not sure how it could be accomplished:
In our project, we're using Keycloak as auth provider, and we are working with JWT auth/refresh tokens. Whenever a request fails with an 401, we request a fresh auth token, and while this request is running, we buffer all incoming requests until the new token arrived. After that, the buffered requests are performed.

I did not find any possibility to intercept the request/response cycle somehow. Is there any option I didn't see?

Thanks!

**Comment by josvegit** [comment]
I had the same question, I realized you can do it in the RestfulProvider, with the **resolve**  and **requestOptions** callbacks.

i.e before you return resolved data => do something and before returning requestOptions, do something

Since RestfulProvider is global for all requests it works like interceptors. I have not tried it fully yet but it should work

**Comment by josvegit** [comment]
Think there is an error callback also, where you should be able to handle http-error codes, not sure about that one though

**Comment by smilexu** [comment]
I have very similar usage, in my react project, I need to get user data and then put into Context. The `resolve` solution works great for me, thanks @josvegit .

**Comment by fabien0102** [comment]
Closed by #254 

Please tell me if this resolution works for you, if not, let's find a better API all together!

**Comment by smilexu** [comment]
@fabien0102 looks good , the onResponse callback on useGet level work great for me. Did you publish the new version? I am using 11.0.0, but seems not have this props on useGet

**Comment by fabien0102** [comment]
I'm on it :wink:

**Comment by smilexu** [comment]
Excellent, thanks for your effort on this library 👍 great job
