### ISSUE TITLE
Provide access to response headers

### ISSUE THREAD

**Issue by ysgk** [contiamo/restful-react#173]
Hi, thanks for this library :)

**Is your feature request related to a problem? Please describe.**
I need access the `X-Total-Count` header for pagination, but no means seems to be provided.

**Describe the solution you'd like**
I want to access response headers. I think [processResponse](https://github.com/contiamo/restful-react/blob/da8882f9582fe5b98db6870a481924abc68b6275/src/util/processResponse.ts) should return `headers` too.

**Comment by fabien0102** [comment]
@ysgk Do you want to give a try for this feature?

**Comment by ysgk** [comment]
@fabien0102 Yes, I will make a PR.

**Comment by ysgk** [comment]
I noticed that `GetState` already has `response` as its property, but it seems to be not implemented yet. Do you have any plan to implement that? If so, `headers` can be easily accessed from it.

https://github.com/contiamo/restful-react/blob/b1d4c8295225721d9ffc6f80eee54f47c4a0a5d8/src/Get.tsx#L133-L138

**Comment by TejasQ** [comment]
@ysgk, that'd be an amazing contribution from you 😻

**Comment by ysgk** [comment]
I think `data` or `error` and their header should be coupled tightly, otherwise we might get the wrong header info as `data` or `error`. That would be tough 😅

**Comment by TejasQ** [comment]
Not sure I agree: we can clear response `headers` on every request initialization and reset them on every request completion – then they're always up to date and in sync.

**Comment by fabien0102** [comment]
Closed by #254 

Please tell me if this resolution works for you, if not, let's find a better API all together!
