### ISSUE TITLE
async/promises for requestOptions in RestfulProvider

### ISSUE THREAD

**Issue by South-Paw** [contiamo/restful-react#180]
### Is your feature request related to a problem?

We use aws-amplify library for auth. To get the current users JWT, we call `Auth.currentSession()` which is a `Promise<User>` where `User` contains a valid JWT (as the lib handles token refresh as well).

The problem is that `RestfulProvider`'s `requestOptions` does not allow for promises or async functions that return `Partial<RequestInit>`.

### Describe the solution you'd like

One of

* `requestOptions` supports async functions

* `requestOptions` supports `Promise<Partial<RequestInit>>` type

* another alternative workaround for this issue

### Describe alternatives you've considered

Current workaround I have in place is to store the JWT in Redux and connect the RestfulProvider to the store to get the JWT for requests.

However, this was an interim workaround and the JWT in Redux is not refreshed when the lib internally refreshes the JWT token - so we get 401's after the first token refresh.

### Additional context

* [Sample of code in solution one](https://user-images.githubusercontent.com/2154764/69096782-f7275900-0ab9-11ea-8cb2-e7add5fe44ae.png)
* [Sample of code in solution two](https://user-images.githubusercontent.com/2154764/69096769-ef67b480-0ab9-11ea-900b-724674b25eec.png)

Any help or feedback is appreciated as well - big thanks for improving the way I write React components 🙌

**Comment by South-Paw** [comment]
@fabien0102 Hi there, thanks for the friendly reply!

If its reasonably straight forward as you say I'd be more than happy to have a go at implementing it.

Do you have any suggestions on where to start with this? I haven't yet had a chance to dig through the code, but maybe an indication of what files I'll need to touch to start the ball rolling

**Comment by fabien0102** [comment]
@South-Paw For this kind of feature, a good start is probably to update the type here -> https://github.com/contiamo/restful-react/blob/master/src/Context.tsx#L21 (so you can see where typescript is complaining ^^)

And after add some unit tests over there -> https://github.com/contiamo/restful-react/blob/master/src/Get.test.tsx#L526 with a promise as `requestOptions` and see what you need to update to make the test happy 😁 

The logic is quite isolate, we have some `getRequestOption` functions (https://github.com/contiamo/restful-react/blob/master/src/Get.tsx#L207), logically with typescript and unit tests, you "just" have to follow the red. Don't hesitate to open a draft in github if you need any help 😉

**Comment by South-Paw** [comment]
I'll discuss with my team tomorrow morning and see about putting some time into it - thanks for the guidance 👍

**Comment by South-Paw** [comment]
Closed with #199 

I've implemented async requestOptions into our app this morning and it seems to be working fine.
