### ISSUE TITLE
React Native support (issue with React peer dependency) 

### ISSUE THREAD

**Issue by owinter86** [contiamo/restful-react#181]
**Describe the bug**
This currently does not work with new React Native projects (non expo) due to RN targeting a specific React Version (currently 16.9.0), so due to the react peer dependency it will install react@^16.8.4 and therefore cause the error shown below.

I can confirm there are no issues if we remove react as a peer dependency, which will ensure when using with React native that two versions of react will not be installed. But unsure if this is a satisfactory resolution.

**To Reproduce**
1. init new react native project (without expo)
2. install react restful
3. try and use any hook

**Expected behavior**
Should support the React Native Projects

**Screenshots**
<img width="540" alt="Screen Shot 2019-11-19 at 11 49 52" src="https://user-images.githubusercontent.com/2920419/69140411-c4359300-0ac2-11ea-9936-187ec838874a.png">

**Comment by South-Paw** [comment]
@TejasQ Looks like this issue can be closed as well as PR has been merged.

**Comment by fabien0102** [comment]
Seams to be fixed, please tell me if not 😉
