### ISSUE TITLE
restful-react import missing flag

### ISSUE THREAD

**Issue by harshzalavadiya** [contiamo/restful-react#185]
**Describe the bug**
`--url` flag does not exist as specified at https://github.com/contiamo/restful-react#import-from-url in README.md

**To Reproduce**
run `npx restful-react import --url https://api.mine.com/openapi.json --output my-awesome-generated-types.tsx`

**Expected behavior**
Command should create typescript interfaces

**Screenshots**
![image](https://user-images.githubusercontent.com/5774849/69337618-51294980-0c87-11ea-97f8-2df59079b340.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by TejasQ** [comment]
Let's release a new version and get this out!

**Comment by TejasQ** [comment]
So if you install `restful-react@latest`, this should now be fixed in v9.3.0.

**Comment by harshzalavadiya** [comment]
@TejasQ, works perfectly. thank you
