### ISSUE TITLE
Progressive Web App (PWA) Fetch Events

### ISSUE THREAD

**Issue by JHibbard** [contiamo/restful-react#189]
Hello, is there a way to trigger a fetch event with restful-react?  My use case is a PWA, where the service worker needs to be able to intercept the fetch event and either allow the network request to proceed or fetch the data from a cache.  Thanks!

**Comment by fabien0102** [comment]
We use fetch internally, so should works out of box 😉 (or I don't get your question ^^)

**Comment by TejasQ** [comment]
@JHibbard, @fabien0102 is right. Every `restful-react` request triggers a `fetch` event so they should be interceptable by your `ServiceWorker1. Could you please provide more info?

**Comment by fabien0102** [comment]
Without more detail, I will close this issue for now (please re-open if I missed something, this is just to clean up a bit 😉)
