### ISSUE TITLE
Jest fails when using RestfulProvider

### ISSUE THREAD

**Issue by Yuhhang** [contiamo/restful-react#194]
Jest fails when using RestfulProvider.

My jest config is default using create-react-app.
**To Reproduce**
test code:
``` js
import React from "react";
import { render } from "@testing-library/react";
import App from "../App";

it("renders index", () => {
  const { getByText } = render(<App />);
  expect(getByText("index")).toBeInTheDocument();
});
```

**Screenshots**
![image](https://user-images.githubusercontent.com/34378268/70062076-58097200-1620-11ea-8818-a9587c95185b.png)

![image](https://user-images.githubusercontent.com/34378268/70061863-fe08ac80-161f-11ea-8dce-2ef01d5b431d.png)

![image](https://user-images.githubusercontent.com/34378268/70062639-5db38780-1621-11ea-9dec-2b17b9be16b4.png)

**Comment by TejasQ** [comment]
This is actually the same issue as #201. Let's continue the discussion there.
