### ISSUE TITLE
UseDelete hook from OpenAPI code adds duplicated trailing slash

### ISSUE THREAD

**Issue by xAlstrat** [contiamo/restful-react#196]
**Describe the bug**
When using useDelete hook generated from open api, running _mutate_ function adds a second trailing slash and a suffix of some data.

    /**
     * This is the kind of function generated from open api automatically.
     */
    const useModelDelete = ({id}) => {
      return useMutate("DELETE", `/model/${id}/`);
    }

Using _mutate()_ sends a DELETE request to /model/some_id//[object Object] instead of /model/some_id/.
Using _mutate('some_id')_ send the request to /model/some_id//some_id.

Using _mutate_ with PUT action works ok (look at the example).

**To Reproduce**
1. Look an example at https://codesandbox.io/s/restful-react-demos-pe03n
2. Click on buttons and see the network log.

**Expected behavior**
Delete request should be sent to /model/some_id/.

Thanks !

**Comment by TejasQ** [comment]
Hey @xAlstrat! Thanks for opening this issue. Hope you had a great holiday season! Would you like to have a try at fixing this with a PR? I'd be happy to help you.

**Comment by xAlstrat** [comment]
I tried the PR sent in my computer, was a trailing slash problem. Thanks you!

**Comment by South-Paw** [comment]
@xAlstrat confirming that your issue has been resolved?

**Comment by xAlstrat** [comment]
Yes ! Thanks!
