### ISSUE TITLE
[Question] How to create a conditional useGet ?

### ISSUE THREAD

**Issue by tonthanhhung** [contiamo/restful-react#205]
I try to achieve something like dependent `useGet` (and save the data to state also) after received the response from the first `useGet`
something similar to this https://github.com/zeit/swr#dependent-fetching
Is it possible now, and how would I do it ?
PS: 
I tried to take advantage of lazy & refetch, eg:
```
{data: user} = useGet({path: pathToGetUser})
{refetch: refecthProject} = useGet({
  path: pathToGetProjectWithUseId, 
  lazy:true, 
  resolve:data=>{
     //save data to state
  }})
if (user && user.id){
  refetchProject() 
}
``` 
That was my idea
but I stuck at how to compose the `pathToGetProjectWithUserId` is ugly and error prone like this
`/api/project/user/{user ? user.id ? -1}`

How would I do the above requirement nicer ?

**Comment by fabien0102** [comment]
I guess we should add a `skip` props as in apollo, if it's `true`, not execute, that's it.

For your use case it will be:

```tsx
const {data: user} = useGet()
const {data: userProject} = userGet({path: `/project/user/${user?.id}`, skip: !user })
```

So, if no user, no request, simple 😁 

Do you want to take care of this issue?

**Comment by fabien0102** [comment]
So I guess `lazy` is actually the way to go (`skip` & `lazy` are the same concept, cf #216)

You can just write:

```tsx
const {data: user} = useGet()
const {data: userProject} = userGet({path: `/project/user/${user?.id}`, lazy: !user })
```
