### ISSUE TITLE
Avoid boilerplate destructuring JSON responses

### ISSUE THREAD

**Issue by seanlaff** [contiamo/restful-react#213]
It's a little painful to destructure a specific field from inside a json response, i.e

```ts
const { data } = useGetRoles({});
const roles: Role[] = data?.roles ?? [];
```

I'd prefer if I could do this in the first line (and also not have to manually type my variable to `Role[]`). I've been trying to figure out if there there's some syntactic sugar with nullish coalescing and object destructuring that gets me there, but so far I've been unsuccessful.

One solution I did find was this 

```ts
const { data: { roles = [] } = {} } = useGetRoles({});
```

However for that default assignment trick to work, `data` has to be `undefined`. Currently restful-react types `data` as `TData | null`

Does it make sense to change the `data` type? Is there another pattern to solve this use case?

**Comment by fabien0102** [comment]
The thing is `data` is `TData | null`, it's `null` on loading and error.

I guess, for this kind of case, we could add a kind of `default` value to avoid the `null`, but by design I like that developers have to think about the loading and error cases (even if it can be annoying 😉)

**Comment by seanlaff** [comment]
Agreed, I don't think it would be appropriate for the library to have a default value since the empty-value case is a signifier of no data. I think the idea Im floating is potentially changing the type of data from `TData | null` to `TData | undefined` since default assignment only works with a strict `undefined`. It's a nuanced thing and would be a breaking change, so I'm not sure if it's worth it 🙂

**Comment by TejasQ** [comment]
> It's a nuanced thing and would be a breaking change, so I'm not sure if it's worth it 🙂

I propose closing this issue and reopening it if this change solves a very significant problem. At the moment, it doesn't seem to.

**Comment by seanlaff** [comment]
Sounds good to me
