### ISSUE TITLE
[9.8.0] Unable to use generation script in latest version

### ISSUE THREAD

**Issue by South-Paw** [contiamo/restful-react#222]
## Describe the bug

`dist/bin/restful-react.js` does not exist in `9.8.0` leading to install errors (#220 and #221)

## To Reproduce

Install from npm and look in the `node_modules/restful-react/dist/bin/` folder - `restful-react.js` is not in there.

## Expected behavior

It should be there 😄

## Additional context

I think that the package has been published without running `yarn build` which would trigger the `build:bin` task. Doing this locally creates the required file:

![image](https://user-images.githubusercontent.com/2154764/72494973-689d4100-388a-11ea-8f9e-c41c13773e46.png)

**Comment by South-Paw** [comment]
@fabien0102 or @TejasQ could one of you fellas look into republishing this (there is also a change relevant in #219) - thanks 👍

**Comment by fabien0102** [comment]
I'm on it! Sorry, was a bit busy over there 😬

**Comment by fabien0102** [comment]
Fixed in `9.9.0`! Thanks for the reporting!

**Comment by South-Paw** [comment]
@fabien0102 I thought you must've been busy - thanks for fixing! ❤️
