### ISSUE TITLE
[Feature Request] Include a Promise Based API in Autogenerated code

### ISSUE THREAD

**Issue by hydrosquall** [contiamo/restful-react#223]
**Is your feature request related to a problem? Please describe.**

- I'd like to use this library in a React project which uses a promise-based API, without rewriting that project to use React hooks. Our data fetching is happening inside of redux thunks, where hooks and JSX components cannot be used.

**Describe the solution you'd like**

Presently, for a given resource called `get-dogs`, `restful-react` generates
  - a hook called `useGetDogs`
  - a React component called `GetDogs`

We'd be interested in generating an additional function called `fetchGetDogs`, which has the same typed `queryParameters` as an input, and returns a promise with the same `responseType` as the other two pieces of generated code.

**Describe alternatives you've considered**

- We could just use the generated types from `restful-react` library, and use with  them another promise-based data fetching library.
- Use the `typescript-fetch` generator instead: https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/typescript-fetch.md (have not tested it yet).

**Additional context**

**Comment by fabien0102** [comment]
Very good idea, and should be quite easy to implement ^^ I'm usually hijack the generated types and write a custom fetch (since we have very few on them on our application) but a more generated way can definitely be awesome!

**Comment by fabien0102** [comment]
You have some `customGenerator` released in `9.10.0`, tell me if you have any feedbacks 😃
