### ISSUE TITLE
UTF-8 charset in response content causing the generator to replace all return types with void

### ISSUE THREAD

**Issue by ChristianIvicevic** [contiamo/restful-react#231]
**Describe the bug**
When defining the responses and using the `application/json;charset=UTF-8` mimetype the code generator fails to correctly type all requests and replaces the return types with `void`.

**To Reproduce**
Create an OpenAPI 3 schema file with this endpoint:
```
paths:
  /api/activities:
    get:
      operationId: getActivities
      responses:
        200:
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                type: array
                description: Unordered list of activity names
                items:
                  type: string
```

**Expected behavior**
I expected the `useGetActivities` hook to return a `string[]`, but it is typed as `void`. Replacing `application/json;charset=UTF-8` with `application/json` fixes this issue.

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.2

**Comment by fabien0102** [comment]
Nice catch, should be quite easy to fix, do you want to take this issue?

**Comment by fabien0102** [comment]
We need to improve a bit this part to be more permissive

https://github.com/contiamo/restful-react/blob/48447507921c60590b30553c740e49cdd64cbfb1/src/scripts/import-open-api.ts#L198-L208

**Comment by fabien0102** [comment]
Was raining outside 🙄 So I fixed it ^^ Should be merge tomorrow 😉
