### ISSUE TITLE
consider moving cli to a separate package (bc of dependencies)

### ISSUE THREAD

**Issue by cztomsik** [contiamo/restful-react#238]
**Is your feature request related to a problem? Please describe.**
`npm i restful-react` downloads quite a lot of dependencies (100?) which is not only waste of time & bandwidth but also makes security auditing much harder.

**Describe the solution you'd like**
Separate package for cli

**Comment by fabien0102** [comment]
.Good point, since we always use the cli I never thought about this.

This could also be a good opportunity to remove the tests from the npm packages.

**Comment by fabien0102** [comment]
https://github.com/contiamo/restful-react/pull/239

This should provide a `without-cli` version

![image](https://user-images.githubusercontent.com/1761469/74652837-36cc1280-5187-11ea-8d61-4bbfd04f76d0.png)


Let me know if everything works as expected 😉

**Comment by cztomsik** [comment]
much better, thanks!
