### ISSUE TITLE
Move to using TypeScript AST for code generation

### ISSUE THREAD

**Issue by vkbansal** [contiamo/restful-react#241]
**Is your feature request related to a problem? Please describe.**
I see that the cli uses string manipulation for code generation. Will you be open to moving that to [using TypeScript AST](https://github.com/microsoft/TypeScript/wiki/Using-the-Compiler-API#creating-and-printing-a-typescript-ast)?

**Describe the solution you'd like**
I was working on something similar and can open a PR, if the authors/maintainers are interested.

**Comment by fabien0102** [comment]
From my experience, using typescript AST is amazing to manipulate an existing code (I use it a lot in another project) but I don't really see the benefits for pure text generation. But I'm always happy to review my positions ^^ can you tell me why you think it will be better with AST? 😃

**Comment by vkbansal** [comment]
I had made something similar to this project for my organization and felt that using AST for code generation is simpler than string manipulation because it takes care of things like bracket balancing, etc.

It's just my personal preference.

**Comment by fabien0102** [comment]
For now I'm prefering the string style, let's see later if it's become unmaintable but for now it's totally good enough (especially with our tests suite)

But thanks for the suggestion 👍
