### ISSUE TITLE
Gatsby static HTML build fails due to dependency on browser API AbortController

### ISSUE THREAD

**Issue by mbrookson** [contiamo/restful-react#242]
**The problem**
I've recently ported my personal site into a Gatsby application to try it out. I love restful-react, but I've hit an issue where the Gatsby static HTML build fails due to restful-react hooks depending on AbortController at the point when the hook is run, rather than when the HTTP request is made. Gatsby suggest any interactions with browser APIs be run inside a `useEffect` so that they run when the browser binds to React, rather than at build time. However, this is happing in a hook so I cannot move it to inside a `useEffect` as it breaks the rules of hooks!

**Potential solution**
Haven't looked at the restful-react source code yet but it seems like creating an instance of AbortController is being done prematurely and should be done at the time of calling the `mutate` function exposed by `useMutate`, for example, rather than when `useMutate` is first run.

**Alternative solutions**
- Allow the restful-react hooks to be fired in a 'mock' way, which stubs them when not running in the browser. Not sure I think this is a good solution though, but would avoid any server-side issues.
- Only allow AbortController and other browser APIs to run in the browser, but still allow the fetching of data without that added functionality when running in a non-browser environment?

**Example usage**
![image](https://user-images.githubusercontent.com/20131783/76164348-1a981180-6146-11ea-8513-9ec0bf3f2e39.png)

**Link to Gatsby docs**
[https://www.gatsbyjs.org/docs/debugging-html-builds/](https://www.gatsbyjs.org/docs/debugging-html-builds/)

**Output of Gatsby build error**

![image](https://user-images.githubusercontent.com/20131783/76164292-a2315080-6145-11ea-9148-7d58b5761afe.png)

**Comment by fabien0102** [comment]
Hi, thanks for the feedback!
This should not be too hard to fix, just make sure than AbortController exists before using it should do the trick.
I'm currently stuck at the hospital (16m free fall at climbing 😅) so I can't really take this issue now, but if you want to open a PR, I can review it 😉

**Comment by mbrookson** [comment]
Hi. I'm working on a fix but want to test locally with my Gatsby build to make sure it's working, however I'm getting an error when running `yarn build` or `yarn watch`. Any ideas?

![image](https://user-images.githubusercontent.com/20131783/76168178-14655d80-6165-11ea-93e8-2ef8fee1f142.png)

**Comment by fabien0102** [comment]
Never had this locally, very strange and no ideas, sorry...

**Comment by mbrookson** [comment]
All I did was fork master, run `yarn` and run `yarn build` 🙁

**Comment by fabien0102** [comment]
Node version maybe? This is running well on my computer and Travis... So... I don't really know what to think

**Comment by mbrookson** [comment]
Yeah it was node version. I was running the latest version. Downgrading to LTS version resolved it.

Here's the issue if you're interested! https://github.com/nodejs/node/issues/32107

**Comment by fabien0102** [comment]
Fixed! Thanks to @mbrookson 😘
