### ISSUE TITLE
Generated by restful-react Does not change type in mutation

### ISSUE THREAD

**Issue by webwmagnet** [contiamo/restful-react#247]
Hello!

**Describe the bug**
Generated by restful-react Does not change type in simple mutation

**To Reproduce**
1. Got yaml or json file
2. Code Generation
3. Check type simple mutation Delete, is "string"

**Expected behavior**
I need the types that were specified from json / yaml to be delivered, otherwise an application error

**Screenshots**

> This is example swagger - https://editor.swagger.io/

Method Delete to /store/order/{orderId} have type:integer 

!['Server swagger'](https://i.paste.pics/8CPNL.png)

Here it compiled restful-react 

!['Server swagger'](https://i.paste.pics/8CPR0.png)

**Comment by fabien0102** [comment]
It's actually a good question, since it's in the path, this is technically always a string!
But I get your point 😄 I guess this will hurt nobody to use "number" instead of "string" in your case, so let's do it!

Can you take care of this? (I'm still stuck at the hospital without computer, but I can review/approved/merged/help on my phone 😉)

**Comment by webwmagnet** [comment]
@fabien0102  Honestly, I tried for a long time, about 5 hours, but I tried to comb it right away in node_module, and nothing came of it, I just can’t find where this Stirng is indicated, changed everything with a search, changed it, found a lot of things where to change, but not that , what I need :(

P.S. Stop getting sick! Get well soon, otherwise your working machine must have missed you very much! : D

**Comment by fabien0102** [comment]
I finally have my computer, back to business!

PS: I'm not sick, I took a 16m fall! 😁 (and apparently I need a bit of rehab 🙄)

**Comment by fabien0102** [comment]
Done! @webwmagnet I hope this will fit your project perfecly! 😃 (I bumped the version just for you ^^)

**Comment by webwmagnet** [comment]
@fabien0102 
Thanks a lot!

It’s just that other developers have adequate REST API and BackEnd, and I have a universal case: D

**Comment by webwmagnet** [comment]
@fabien0102  Damn, everything is fine, only the swagger type number gives an integer and this makes an error  :( 
![Problem](https://i.ibb.co/nM92QYk/2020-03-23-14-33-27.png)

**Comment by fabien0102** [comment]
Good catch, I think I used the value without resolved it 😬

**Comment by fabien0102** [comment]
Fixed is `10.0.1`!

**Comment by webwmagnet** [comment]
@fabien0102  You are a wizard. Thanks!)
