### ISSUE TITLE
Docs on auth?

### ISSUE THREAD

**Issue by GitToby** [contiamo/restful-react#248]
**Is your feature request related to a problem? Please describe.**
Great toolkit, but I can't work out how to pass stateful auth to a request

**Describe the solution you'd like**
some clearer docs then the one example is given

**Describe alternatives you've considered**
googling, trading type descriptions

**Additional context**
none

**Comment by fabien0102** [comment]
Hi! This is really depends which auth is used (cookies, bearer token...)

Usually the idea is to make a request to the API, retrieve a token, store it somehow (cookie or localstorage for example) and add this token as header in restful-react provider (so it's apply to every requests)

I should retrieve my computer tomorrow 🤞I will write you a little code example as soon as I have access to my computer (I don't have the courage to do it on my phone 😅)

In between if you can give me a bit more information on your stack, so I can personalized a bit more the example 😉

Have a good evening

**Comment by fabien0102** [comment]
So, quick example on codesandbox for you

Backend:
https://codesandbox.io/s/great-cray-9z48i

Frontend:
https://codesandbox.io/s/clever-curran-kgg0y

Please note that this is just an example to show you the different concepts, I took a lot of shortcuts to simplify the code and focus on the "how auth works" 😉 

Tell me if something is still not clear, the main idea is to set the correct headers in restful-react provider and after everything follow.

Note: you may need to start the backend, codesandbox put backend code in hibernation quite quickly.

**Comment by GitToby** [comment]
That's really useful thanks! I realised now what I meant by auth was really how I can attach dynamic headers to the requests. looks like I was totally overlooking the fact you can attach stateful headers to the component.

I saw the below in the docs and was tearing my hair out trying to work out where the `authToken`  param came from.

```Javascript
requestOptions={authToken => ({ headers: { Authorization: authToken } })}
```


in the end, I might have overdone it. This is a global wrapper for the app as I couldn't pass tokens just when I need them on the back end:

```javascript 
useEffect(() => {
    auth0.isAuthenticated &&
      auth0
        .getTokenSilently()
        .then((res: string | undefined) => setAuthToken(res));
  }, [auth0]);

  return (
      <RestfulProvider
        base={API_HOST_ROOT}
        onError={(err) => {
          notification.warn({
            message: 'An Error occurred',
            description: err.data.detail,
            duration: 10,
            placement: 'bottomRight'
          });
        }}
        requestOptions={
          authToken
            ? {headers: {Authorization: `Bearer ${authToken}`}}
            : undefined
        }
      >
<RestOfApp/>
</RestfulProvider>
```

But I did manage to fix it, thanks for your thorough response!
