### ISSUE TITLE
provide access to the context values

### ISSUE THREAD

**Issue by ysgk** [contiamo/restful-react#250]
**Is your feature request related to a problem? Please describe.**
I want to create a custom hook that uses `base` value passed to the Context, but currently there is no such functionality provided.

For example:

```tsx
import { useRestfulContext } from 'restful-react'


const useMyOriginalHook = () => {
  const { base } = useRestfulContext()
  // ... My original request logic
}

```

**Describe the solution you'd like**
It would be nice if restful-react could provide such a hook or export the Context itself.

**Describe alternatives you've considered**
There seems no alternative unless the Context is exported.

**Comment by fabien0102** [comment]
This seams totally overkill, why are you not just exporting `base`?

```tsx
export base = "https://my-api.com"
```

And you are good to go!

If you want something more fancy to deal with you config, I can also suggest https://github.com/contiamo/react-runtime-config 😇 
My little homemade solution, works very smoothly 😃

**Comment by ysgk** [comment]
OK, I'll look into it. Thanks.
