### ISSUE TITLE
Ability to provide path params to mutate method when using useMutate

### ISSUE THREAD

**Issue by vkbansal** [contiamo/restful-react#255]
Right now there is no way to provide path params when `mutate` is called.

```ts
/* generated code */
export const useUpdatePet = ({id, ...props}: UseUpdatePetProps) => 
  useMutate<Pet, Error, void, UpdatePetRequestRequestBody>("PATCH", `/pets/${id}`, props);

/* usage */
const { mutate } = useUpdatePet({ id: '' })

async function handleUpdate() {
  await mutate() // -> Right now we cannot pass id dynamically here
}
```
This causes issue when using it in with data-tables and grids.

I do not want to render/use hooks for each row individually. I would like to render/use it once in the parent component and pass the path params when I call mutate.

I have made a rough implementation for the same [here](https://github.com/vkbansal/restful-react/commit/7f8882b00711c2c3716ff69b49d66a4d8fccc059).

**Comment by smilexu** [comment]
I have exact same issue here

**Comment by vkbansal** [comment]
I'll try opening a PR over the weekend.

**Comment by sytolk** [comment]
Documentation and override path parameter is missing here: https://github.com/contiamo/restful-react/tree/96fd1193d63c257feb7cfe9331c5447cd391b8be#mutations-with-usemutate
