### ISSUE TITLE
Support `queryParamStringifyOptions` for customGet

### ISSUE THREAD

**Issue by stereobooster** [contiamo/restful-react#263]
**Is your feature request related to a problem? Please describe.**

The same way as we support `queryParamStringifyOptions` for hooks, we need to support it for getters

**Describe the solution you'd like**
Add one more param

**Describe alternatives you've considered**
none

**Additional context**
N/A

**Comment by fabien0102** [comment]
All the code for `customGet` live outside of restful-react since it's custom (so on the user side)

You just need to add this in our fetchers.ts 😉:

![image](https://user-images.githubusercontent.com/1761469/80977094-8fc15380-8e24-11ea-9875-8ffab4aaa515.png)

**Comment by stereobooster** [comment]
I'm talking about functions generated by restful-react

```
export const searchResources = (
  {
    projectId,
    ...props
  }: ... ,
  signal?: RequestInit["signal"],
) =>
  customGet<...>(..., props, signal);
```

**Comment by fabien0102** [comment]
So, as said before this code is generated on the user side (as shown in our example):

https://github.com/contiamo/restful-react/blob/12d905cf848bdcee6362b6aaaf496dd3d1f90d63/examples/restful-react.config.js#L24-L40

But, what you are searching for is in `fetchers.ts` (in contiamo-ui), and my bad I did forgot to mention that you also need to update `CustomGetProps`.

Bellow the full diff to to have the `queryParamStringifyOptions` available in contiamo-ui:

```diff
diff --git a/src/queries/fetchers.ts b/src/queries/fetchers.ts
index 6d04989..2892d15 100644
--- a/src/queries/fetchers.ts
+++ b/src/queries/fetchers.ts
@@ -18,6 +18,7 @@ export interface CustomGetProps<
   }
 > {
   queryParams?: TQueryParams;
+  queryParamStringifyOptions?: qs.IStringifyOptions;
 }
 
 export const customGet = <
@@ -28,12 +29,12 @@ export const customGet = <
   }
 >(
   path: string,
-  props: { queryParams?: TQueryParams },
+  props: { queryParams?: TQueryParams; queryParamStringifyOptions?: qs.IStringifyOptions },
   signal?: RequestInit["signal"],
 ) => {
   let url = path;
   if (props.queryParams && Object.keys(props.queryParams).length) {
-    url += `?${qs.stringify(props.queryParams)}`;
+    url += `?${qs.stringify(props.queryParams, props.queryParamStringifyOptions)}`;
   }
   return fetch(url, {
     credentials: "include",
```
Have fun 😉
