### ISSUE TITLE
Generated API add text/plain to content-type header request

### ISSUE THREAD

**Issue by ricardona** [contiamo/restful-react#264]
**Describe the bug**
Generated API hook is adding `text/plain` to `content-type` header. 

**To Reproduce**
Generate API using the next definition:
``` yaml
post:
    tags:
        - security
        - legacy
    responses:
        '200':
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/MenuItems'
            description: Success
    operationId: postGetMenu
```

Headers are set as follows:
``` ts
  const myHook = usePostGetMenu({
    requestOptions: { headers: { 'Content-Type': 'application/json', Accept: 'application/json' } }
  })
```
And I make the request:
``` ts
    myHook.mutate().then((value: MenuItems) => {
      console.log(value)
    })
```

**Expected behavior**
I expect the request header to have `content-type: application/json` and not `content-type: text/plain, application/json`
![image](https://user-images.githubusercontent.com/535890/81018048-50e1cc80-8e29-11ea-8877-9a698bfdf030.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Browser Chrome 80

Thanks in advance.

**Comment by AsasInnab** [comment]
I have the same issue. It seems impossible to replace content-type, it's just appending the types.

**Comment by valstu** [comment]
Noticed the same today. I have set `'Content-Type': 'application/json'` on the <RestfulProvider /> and I am trying to override it on the component level on my `useMutate()` hook to `multipart/form-data` but encoutered the same issue. Sent content type was `application/json, multipart/form-data` 🤔

**Comment by fabien0102** [comment]
Interesting indeed, will have a look

**Comment by fabien0102** [comment]
I bet on a browser behaviour for the merge of `Content-Type` and `content-type` (since we didn't code anything for this ^^)
