### ISSUE TITLE
onResponse and reading body

### ISSUE THREAD

**Issue by torkelrogstad** [contiamo/restful-react#273]
**Is your feature request related to a problem? Please describe.**
I want to intercept requests, and doing actions based on the response in certain endpoints, **for all requests, not in the component that calls that request**. 

An example of this: I hit my auth endpoint, and receive a JWT. This JWT should then be appended to my headers.

My attempt:  add `onResponse`, and get the body. 

The problem: ` TypeError: Response.json: Body has already been consumed.`

**Describe the solution you'd like**
Instead of doing `onResponse(response)`, do `onResponse(response.clone())`, **before** reading the body.

**Comment by fabien0102** [comment]
Sounds good, do you want to take care of this?
