### ISSUE TITLE
Support queryParamStringifyOptions on RestfulProvider level

### ISSUE THREAD

**Issue by ApacheEx** [contiamo/restful-react#278]
**Is your feature request related to a problem? Please describe.**
I think the logic should be similar to `queryParams` (e.g. you can have `lang` which will be added to each request automatically). I'd like to have the same possibility for `queryParamStringifyOptions`, in my case I need to use `{ arrayFormat: 'brackets' }` for each request. It's not comfortable to specify this parameter each time I use array in `queryParams`.

**Describe the solution you'd like**
The same as we have with `queryParams`:
![image](https://user-images.githubusercontent.com/1918108/85827957-f6614e80-b78f-11ea-8cda-167f39621022.png)

**Describe alternatives you've considered**
Currently, we can add `queryParamStringifyOptions` to each request where array is used. But as I mentioned, I don't like it :)

**Additional context**
I think it's clear enough already

p.s thanks for awesome library.

**Comment by fabien0102** [comment]
This is a very smart idea! I'm also have the issue but with `arrayFormat: "comma"` 😁 (I don't know why I didn't thought about this myself ^^)
