### ISSUE TITLE
useMutate with DELETE verb should handle body if it's obejct

### ISSUE THREAD

**Issue by ApacheEx** [contiamo/restful-react#288]
**Is your feature request related to a problem? Please describe.**
Yeah, it is. We have use case where DELETE request accepts json body. 
Currently, I see that `useMutate` can't handle body if it's not a string:

- https://github.com/contiamo/restful-react/blob/454db37e029fdd3b8fceb98a6dc977720a91cb0b/src/useMutate.tsx#L119-L127
 
- https://github.com/contiamo/restful-react/blob/454db37e029fdd3b8fceb98a6dc977720a91cb0b/src/useMutate.tsx#L132-L134

**Describe the solution you'd like**
If `body` is a string then we apply the logic as it is now (append to the path). Otherwise, we use it as in regular request (i.e. `options.body`). I can prepare PR, but just let me know if it makes sense for you.

**Describe alternatives you've considered**
Currently, the only way to do it - is to change rest service (e.g move request body to query params), but it's not always possible.

based on https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE:
![image](https://user-images.githubusercontent.com/1918108/89514072-097b2b80-d7de-11ea-80e8-a63703c7f960.png)

**Comment by ApacheEx** [comment]
@fabien0102 any ideas? 🤔

**Comment by micha-f** [comment]
@ApacheEx - FYI @fabien0102 is enjoying a well-deserved summer vacation and it might take a couple more days for him to get back

**Comment by ApacheEx** [comment]
well, it's not critical, thanks for update 👍 
having rest is important 🏖️

**Comment by fabien0102** [comment]
@ApacheEx This should be doable and the request is totally reasonnable 😁 

Can you try to open a PR for this, since we don't have the case internally, this issue will not be top priority (to be totally transparent with you), but I will be very happy to help you and review a nice PR 😃
