### ISSUE TITLE
How to customise fetch calls?

### ISSUE THREAD

**Issue by stereobooster** [contiamo/restful-react#292]
Hey :)

It seems there was a way to customize which fetch library to use. But I can't find documentation for it. Can you remind me how to do this?

**Comment by fabien0102** [comment]
https://github.com/contiamo/restful-react/blob/5c3bf6684a1a5a589c7ea0975804edae299c8b8a/src/useGet.tsx#L136

This is not possible, we are using the `window.fetch` directly, but you can use the mock feature for testing (still a bit alpha)

https://github.com/contiamo/restful-react/blob/5c3bf6684a1a5a589c7ea0975804edae299c8b8a/src/useGet.tsx#L45-L49

**Comment by stereobooster** [comment]
Nah it's no gonna work for my case I will need to find workaround. Thanks!
