### ISSUE TITLE
The github releases are not in sync with npm versions

### ISSUE THREAD

**Issue by cbek** [contiamo/restful-react#298]
**Is your feature request related to a problem? Please describe.**
Currently, all pushes on master branch ends in npm publish.
This leads to inconsistency between [npm packages ](https://www.npmjs.com/package/restful-react/)and [GitHub](https://github.com/contiamo/restful-react/releases).

**Describe the solution you'd like**
Only git tags leads to an npm publish.

**Comment by fabien0102** [comment]
The solution wanted for this issue:

> The flow I would like to have in place is the following:
>
> * any contributor can bump the version on the package.json in a PR
> * as soon as this PR is merged, if the package.json was updated -> publish to npm
> * draft a github release with a nice changelog **<- the missing part!**

https://github.com/contiamo/restful-react/pull/299#issuecomment-703469233

**Comment by fabien0102** [comment]
As we can see here -> https://github.com/contiamo/restful-react/releases/tag/v15.0.0

This is done! Now every publish to npm will be followed by a github release (with the associated changelog) 🎉

**Comment by cbek** [comment]
Good work. ❤️
