### ISSUE TITLE
Multiple useGet() hooks in a component - how to prevent re-render?

### ISSUE THREAD

**Issue by SlowburnAZ** [contiamo/restful-react#312]
So, let's say I've got a component with the need to fetch data from multiple endpoints, and hence use multiple useGet() hooks.

Is there a way to prevent the re-rendering of the components until all results come back?

For example, I'm doing something like this:
```
const MyComponent = () => {
  const { data: results1 } = useGet({
    path: someEndpoint,
    loading: results1Loading
  });

  const { data: results2 } = useGet({
    path: someOtherEndpoint,
    loading: results2Loading
  });

  return results1Loading || results2Loading ? (
    <Loading />
  ) : (
    ...my component's content...
  )
};
```

It would be nice to be able to "wait" on both result sets to come back before causing a re-render, but it's not clear to me how to do this.

**Comment by fabien0102** [comment]
Short answer, no, this is not possible with `useGet`, sorry. In our product we are just using a simple Promise version of the generated component to handle these avanced usecases. Or we are just doing like you example and combined the `loading`.

**Comment by SlowburnAZ** [comment]
Thanks...  I'll keep on keeping on with that strategy.
