### ISSUE TITLE
Mocking useMutate when using Jest

### ISSUE THREAD

**Issue by SlowburnAZ** [contiamo/restful-react#316]
Are there any examples available for how to test a component that uses the useMutate() hook in Jest?

I get that there's the `mock` prop that can be set, but when trying to use this in a test, I'm getting the "Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component." error.

**Comment by fabien0102** [comment]
Hello @SlowburnAZ ,
We don't have any example in this repository, but I can help you 😃 
To test some hooks (including restful-react ones) with jest, the easiest way this it use this library -> https://github.com/testing-library/react-hooks-testing-library

So with `useMutate()` this should look like something like this:

```tsx
import { renderHook, act } from "@testing-library/react-hooks";
import { useMutate } from "restful-react";

describe("useMutate example", () => {
  interface Data {
    ok: true;
  }
  interface Error {
    message: string;
  }

  interface QueryParams {
    id: string;
  }

  it("should return the mock value", async () => {
    const { result } = renderHook(() =>
      useMutate<Data, Error, QueryParams, {}, {}>("POST", "https://my-api.com", {
        mock: { mutate: async () => ({ ok: true }) },
      }),
    );

    const response = await result.current.mutate({}, { queryParams: { id: "test" } });

    expect(response.ok).toBe(true);
  });
});
```

I hope that this answer your question. For a real world example, this is a little screenshot of my current feature:
![image](https://user-images.githubusercontent.com/1761469/97910452-0c88a800-1d4a-11eb-8c4e-d1244f915952.png)

So I have some `useGet` in my `useGlossaryTreeData` hook, and I just give the `mock` value as props to be able to test my hook logic without having to do real request or mock the network layer.

**Comment by SlowburnAZ** [comment]
Thanks for the help, @fabien0102 ...

I'll play around with this a bit.

**Comment by SlowburnAZ** [comment]
This helped
