### ISSUE TITLE
DIsable OPTIONS Request After each Request

### ISSUE THREAD

**Issue by mskzo** [contiamo/restful-react#321]
How can the request type OPTION that is performed before each request or refetch be disabled?  
Why the lib is doing this kind of request, even for well-defined request types such gets in useGets? 

Best Regards

**Comment by micha-f** [comment]
This sounds like a [preflight request](https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request) (MDN).

It is sent by the browser to determine if the actual request is safe to send.

This is a CORS issue (standard browser behavior for cross-domain requests). We have no influence on this in this library.

More references

* https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Preflighted_requests
* https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Simple_requests

**Comment by micha-f** [comment]
@mskzo closing this as I believe we can't do anything about this. Please feel free to reopen if you disagree.
