### ISSUE TITLE
Handling Bad Request (400 error) response in useMutate()

### ISSUE THREAD

**Issue by SlowburnAZ** [contiamo/restful-react#325]
When using the useMutate hook to delete a resource via my API, an error appears in the browser console if the endpoint returns a 400 error.

In my case, I'm using useMutate to delete a user using the DELETE verb.  If that user is trying to delete itself, the API returns a 400 error.  It seems this situation isn't handled properly, maybe?  In my browser's console, I see the following error:
![image](https://user-images.githubusercontent.com/5659169/102132965-992a8980-3e11-11eb-81ae-cfe33c57c64a.png)

If I look to line 163 in useMutate.tsx in Sources, I can see this:  
![image](https://user-images.githubusercontent.com/5659169/102133425-50bf9b80-3e12-11eb-88bc-986b96da67f4.png)

Am I missing something, or is this a bug?

**Comment by fabien0102** [comment]
![image](https://user-images.githubusercontent.com/1761469/102225057-0cea9600-3ee7-11eb-99ef-df96933fb1ed.png)

This is normal, this is how chrome works, you can hide those errors if you want 😉

**Comment by SlowburnAZ** [comment]
Doh!  Okay.  ;-)
