### ISSUE TITLE
Mutation function inside a useEffect

### ISSUE THREAD

**Issue by omegafranco** [contiamo/restful-react#327]
I'm trying to use a mutate function inside a useEffect. Since I have the exhaustive-deps lint rule, i need to add this function to the depency list in my effect. But the mutate function  reference is changing every render and is triggering my effect.

To work around this I had to memoize the mutation in a useCallback and used that as a depedency instead. Is this the expected path to take? It seems like a lot of overhead. Given the same args, shouldn't we receive the same reference from useMutate in every render?

**Comment by fabien0102** [comment]
Hello, thanks for the reporting, this is probably the same kind of mess than this issue https://github.com/contiamo/restful-react/issues/186

Sadly I don't have any quick win / time for this right know, but I totally agree that this can be an issue! So yeah, for now, eslint ignore or useCallback is the way to go. Sorry for the overhead 😕

**Comment by amacleay-cohere** [comment]
This likely can close given #186 should be resolved
