### ISSUE TITLE
Optional keys of queryParams are not typed properly

### ISSUE THREAD

**Issue by karolinkas** [contiamo/restful-react#332]
**Describe the bug**
I am not 100% sure if this is a bug but when I use one of the autogenerated react hooks and I try to set optional queryParams with the spread operator, here the optional parameter is `filename` then the typescript verification of the these queryparams isn't working correctly.  I only want to set the filename queryParam if there's a searchString. For example if the spelling is `fileName` instead of `filename` I would not get an error in the Typescript compiler. 
```
const {data, error, loading, refetch} = useIngestions({
    queryParams: {
      ...(searchString && {filename: searchTerm.searchString}),
    },
  })
```
For example if the spelling is `fileName` instead of `filename` I would not get an error in the Typescript compiler. I would get one if the queryParam wouldn't be optional though like in: 
```
const {data, error, loading, refetch} = useIngestions({
    queryParams: {
      {fileName: searchTerm.searchString},
    },
  })
```

**To Reproduce**
1. Pick an autogenerated hook.
2. Try to add optional queryParams that don't actually exist and compile ( or use Typescript plugin of your editor )
3. See that it doesn't complain about a wrong key of the queryParams object.

**Expected behavior**
All keys should be typechecked when calling hook with queryParams.

**Comment by mpotomin** [comment]
@karolinkas Would a ternary expression instead of `&&` work for your use case? Something like: 
```
const {data, error, loading, refetch} = useIngestions({
    queryParams: searchString ? {filename: searchTerm.searchString} : undefined
  })
```

**Comment by karolinkas** [comment]
Thanks a lot @mpotomin, that does work, but only if there's exactly one queryParam and really I do have more I just simplified it for this example, but thanks a lot.

**Comment by mpotomin** [comment]
@karolinkas If there are many conditions to consider, it could make sense to use a separate function to combine them into `ExpectedQueryParamsType` in a type-safe way : 
```
getIngestionsQueryParams = (params): ExpectedQueryParamsType | undefined => {
 // conditional logic, spreading params, returning `ExpectedQueryParamsType` or `undefined`
}
```

**Comment by karolinkas** [comment]
Oh wow, I have just done exactly that and it's not checking the types of the params either. I'm in shock, is that a typescript issue? 
```
  const getQueryParams = (): IngestionsQueryParams => {
    return {
      ...(searchTerm.searchString && {filename: searchTerm.searchString}),
      ...(pagination ? {offset: pagination.offset, limit: pagination.limit} : {limit: 50, offset: 0}),
    }
  }

  const {data, error, loading, refetch} = useIngestions({
    queryParams: getQueryParams(),
  })
```

**Comment by mpotomin** [comment]
Could be something with the TS configuration. Please check if [Strict Checks](https://www.typescriptlang.org/tsconfig) are enabled in your `tsconfig.json`.

**Comment by mpotomin** [comment]
Closing as not related to the library

**Comment by karolinkas** [comment]
FYI what we ended up doing is adding a helper function to double check the types manually because there's a known typescript issue where, when using the spread operator, types don't get checked properly.
The helper is:
```
export const ensurePartial = <T>(value: Partial<T>): Partial<T> => {
  return value
}
```
and we use it like follows:
```
const {data, error, loading, refetch} = useIngestions({
    queryParams: searchString && ensurePartial<TypeOfQueryParams>({filename: searchTerm.searchString})
  })
```

**Comment by mpotomin** [comment]
Happy it worked for you! Thank you for letting us know 👍
