### ISSUE TITLE
Poll is giving CORS error

### ISSUE THREAD

**Issue by fengxia41103** [contiamo/restful-react#344]
**Describe the bug**

Using the `Poll` accessing backend API running on the same host (`localhost:8003` to be precise), and fetching data is failing w/ CORS error.

Error message in the Chrome console:

```plain
Access to fetch at 'http://localhost:8003/api/v1/stocks' from origin 'http://localhost:3000' has been blocked by CORS policy: Request header field prefer is not allowed by Access-Control-Allow-Headers in preflight response.
```

**To Reproduce**

Here is my REACT code. This is part of a REACT component:

```javascript
  return (
    <Poll
      path={api + encodeURI(resource)}
      resolve={data => data && data.objects}
    >
      {(data, { loading }) =>
        loading ? <CircularProgress /> : render_data(data)
      }
    </Poll>
  );
```

whereas:

- `api`: is a string "http://localhost:3000/api/v1`
- `resource`: is a string "/devices"
- `render_data`: is a function that will use the resp data to render this page.

**Expected behavior**
Expect Poll will get a list of `devices` from API.

**Screenshots**
None

**Additional context**

Backend can be accessed in the same browser to `http://localhost:3000/api/v1/devices` successfully. Tried using `useGet` (shown below) instead of `Poll`, and it worked. 

```javacript
import React from "react";
import CircularProgress from "@material-ui/core/CircularProgress";
import { useGet } from "restful-react";
import NotFoundView from "src/views/errors/NotFoundView";

function Fetch(props) {
  const { api, resource, render_data, mounted } = props;

  const { data, loading, error } = useGet({
    path: api + encodeURI(resource),
    debounce: 200,
  });

  if (loading) return <CircularProgress />;
  if (error) return <NotFoundView />;

  // if caller is not mounted anymore, quit
  if (mounted && !mounted.current) return null;

  // everything is good, render
  return render_data(data);
}

export default Fetch;

```

I have also set header in the backend to allow CORS, but have no luck. I think there is something about the Google Chrome that is blocking. 

Need advice.

**Comment by fabien0102** [comment]
Hi @fengxia41103,

sorry I totally missed this issue, can you compare what headers are sent between `useGet` and `Poll`, this may help to identify the issue.

**Comment by fengxia41103** [comment]
Hi Fabien0102,

I'm trying to use Poll again in a different project. Issue remains. Here are the request headers from two calls, one using `useGet`, and the other `<Poll`. Both are in the same REACT frontend calling the same Django DRF backend.

All info are copied from browser debugger.

## useGet

The `General` section:
```
Request URL: http://localhost:7001/api/dcim/devices/?limit=0&offset=0
Request Method: OPTIONS
Status Code: 200 OK
Remote Address: [::1]:7001
Referrer Policy: strict-origin-when-cross-origin
```

The `Request Headers` section:
```
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,zh;q=0.8,zh-CN;q=0.7
Access-Control-Request-Headers: authorization,content-type,x-csrftoken
Access-Control-Request-Method: GET
Cache-Control: no-cache
Connection: keep-alive
Host: localhost:7001
Origin: http://localhost:3000
Pragma: no-cache
Referer: http://localhost:3000/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36
```

## Poll

The `General` section:

```
Request URL: http://localhost:7001/api/plugins/lenovo/tasks
Referrer Policy: strict-origin-when-cross-origin
```

and the "Request `Headers`` section:

```
Provisional headers are shown
Learn more
Authorization: Token ac360113831538733babfe71a4fe0ce666122594
content-type: application/json
DNT: 1
Prefer: wait=60s;
Referer: http://localhost:3000/
sec-ch-ua: "Google Chrome";v="95", "Chromium";v="95", ";Not A Brand";v="99"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Linux"
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36
X-CSRFToken: DyaOgn8Y5xmqSXkLFrRmhzUHALFtiMACx3oaH63MvHy54YgmNZ511XBvDMmgSeIV
```

**Comment by fengxia41103** [comment]
Update. Hope this could help someone.

The issue is not in this took, but the `djang-cors-header`. In `settings.py`, one must set all these three:

```
CORS_ALLOW_HEADERS = ['*']
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = False
```

The poll gets the data as expected.
