### ISSUE TITLE
Bundling delete mutations with Promise.all doesn't work after 15.1.3 release

### ISSUE THREAD

**Issue by dcruzin** [contiamo/restful-react#347]
**Describe the bug**

This was working on version 15.1.2:

```
const { mutate: deleteExample } = useMutate({
    verb: 'DELETE',
    path: `/examples`,
});

Promise.all(selection.map(id => deleteExample(id))).then(() => {
    console.log('success')
});
```

In version >= 15.1.3, this results in all requests being canceled.

**To Reproduce**
Just bundle 2 or more delete mutations inside `Promise.all`.

**Expected behavior**
All DELETE requests should be successful and `Promise.all` should be resolved.

**Comment by fabien0102** [comment]
Interesting, I need to try this!

**Comment by fabien0102** [comment]
Indeed,
This is due to this line:
https://github.com/contiamo/restful-react/blob/7f1f69b358a248a9a55fe58f5717622bc1d304ad/src/useMutate.tsx#L101

And this is the test to isolate the behaviour:
```ts
it("should works with Promise.all", async () => {
      nock("https://my-awesome-api.fake")
        .delete("/1")
        .reply(200, { id: 1 });
      nock("https://my-awesome-api.fake")
        .delete("/2")
        .reply(200, { id: 2 });
      nock("https://my-awesome-api.fake")
        .delete("/3")
        .reply(200, { id: 3 });
      nock("https://my-awesome-api.fake")
        .delete("/4")
        .reply(200, { id: 4 });
      nock("https://my-awesome-api.fake")
        .delete("/5")
        .reply(200, { id: 5 });

      const wrapper: React.FC = ({ children }) => (
        <RestfulProvider base="https://not-here.fake">{children}</RestfulProvider>
      );
      const { result } = renderHook(() => useMutate("DELETE", "", { base: "https://my-awesome-api.fake" }), {
        wrapper,
      });
      const results = await Promise.all(["1", "2", "3", "4", "5"].map(i => result.current.mutate(i)));

      expect(results).toEqual([{ id: 1 }, { id: 2 }, { id: 3 }, { id: 4 }, { id: 5 }]);
    });
    ```

The thing is, I'm not sure about removing this `abort()` if this is loading. In some case, this is avoiding to stress the backend, when your user click a lot of times. With long request, this can also permit the user to quickly fix a mistake.
I will ask around to have a nice idea to handle all cases (maybe a new `props` to tweak the behaviour)

**Comment by mpotomin** [comment]
I guess the original idea was that restful-react intentionally has the cancellation policy baked in: if any of the `props` change -> previous request cancelled -> new request fired. Such behaviour seems legit to me and useful for most use cases.

It could indeed be a nice additional feature though: separate flag to disable request cancellation.

**Comment by dcruzin** [comment]
Any news? I need to use a newer release of this lib, but I can't do it because of this :cry:

**Comment by fabien0102** [comment]
Let's see if I can find a nice prop name for this

**Comment by fabien0102** [comment]
@dcruzin Did you try with the latest version? The unit test I posted before is passing without changing the codebase 🤔

This was maybe solved by https://github.com/contiamo/restful-react/pull/338

**Comment by dcruzin** [comment]
It works! Also, congrats on this awesome project. Great time saver!
