### ISSUE TITLE
`--github` flag seems to no longer work

### ISSUE THREAD

**Issue by azrosen92** [contiamo/restful-react#357]
**Describe the bug**
When running `restful-react import --github "username:repo:branch:path/to/openapi.yaml"`, the CLI always errors out with `(node:77636) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'text' of null`. This used to work, and nothing has changed about my configuration, so I'm wondering if there's been a change to the Github API which has broken this feature?

I printed out the response body in the restful-react script and it's returning
```
{
  "data": {
    "repository": {
      "object": null
    }
  }
}
```

It appears to be failing at this line, which tries to access to text from the returned file – https://github.com/contiamo/restful-react/blob/master/src/bin/restful-react-import.ts#L212.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.17

**Smartphone (please complete the following information):**

**Additional context**

**Comment by fabien0102** [comment]
Hello,
can you make sure that your github token is up-to-date with the correct permission? (this is usually the case for this kind of error)

Anyway, I need to improve the error feedback for permission issues

**Comment by azrosen92** [comment]
Thank you! I think I found the permissions issue – I updated the README to fix it here https://github.com/contiamo/restful-react/pull/358
