### ISSUE TITLE
Provider error handling

### ISSUE THREAD

**Issue by fabien0102** [contiamo/restful-react#47]
### Goal

Having a simple and global pattern to catch application errors.

The idea is the following:

```jsx
<RestfulProvider base="https://my-awesome-api.fake" onError={onError}>
  <Get path="">
    {children}
  </Get>
</RestfulProvider>
```

On every error (in `Get`, `Mutation`, `Poll`) the `RestfulProvider.onError` is called with the classic `{data: response, message: ""}`

This will permit to have a centralize way to handle every errors, and because it's an event, we can also simply add a state to stack / dismiss errors like this:

```jsx
class App extends React.Component {
   state = {
     errors: []
  }
  onError(err) {
     this.setState(prev => ({errors: [err, ...prev.errors]}))
  }
  onDismiss() {
     this.setState(prev => ({ errors: prev.errors.slice(1) }))
  }
  render() {
  <RestfulProvider base="https://my-awesome-api.fake" onError={this.onError}>
   {this.state.errors.length && <Progress error={this.state.errors[0].message} onClose={this.onDismiss} />
    <Get path="">
      {/* children */}
    </Get>
  </RestfulProvider>
  }
```

### Questions

1. Sometime we need to handle error locally with the classic pattern (for a better UX basically)

For this I propose a to add a `localErrorOnly` props to `Get`, `Mutate`, `Poll` to avoid the bubbling to the provider.

```jsx
// this request will trigger the provider `onError` on error
<Get path="">{/* children */}</Get>

// this request will NOT trigger the provider `onError` on error
<Get path="" localErrorOnly>{/* children */}</Get>
````

2. Do we add the same logic for `loading`?
```ts
onLoading: (nbOfActiveLoading: number) => void
```

and a bunch of `localErrorOnly`, `localLoadingOnly`, `localOnly` for our components

**Comment by TejasQ** [comment]
I think this makes sense, but the coupling between this library and operational presented in 

```js
{this.state.errors.length && <Progress error
```

from your description is something I'd like to avoid.

I like the `localErrorOnly`. I don't currently see a use case for `onLoading` yet. Do you?

**Comment by fabien0102** [comment]
For the `onLoading`, I want to say same as `onError`, the idea is to have only one place for dealing with this `<Progress />` as a default behaviour. And after `localLoadingOnly` if we want a special loading behaviour (a spinner in a button for example)

**Comment by fabien0102** [comment]
The main remaining problem is that we often need to wait the loading to show the data, so basically:
```jsx
<Get>{(data, {loading}) => loading ? <Progress /> : <MyView data={data} />}</Get>
```

So it's not really helpful…

**Comment by TejasQ** [comment]
Let's not spend too much time here because Suspense will solve this quite nicely. https://github.com/facebook/react/issues/13206

**Comment by fengxia41103** [comment]
What's the current status of this now?

**Comment by fabien0102** [comment]
@fengxia41103 You have a global `onError` at the provider level (https://github.com/contiamo/restful-react#restfulprovider-api), and a `localErrorOnly` at the component level if you want to not bubble up the error (for some nice local error handling).

Is this answering your question?
