### ISSUE TITLE
The response is never passed

### ISSUE THREAD

**Issue by Xiot** [contiamo/restful-react#6]
**Describe the bug**
The 'response' object is never passed into setState, so it will never be available through the render prop.

**To Reproduce**
https://github.com/contiamo/restful-react/blob/master/src/index.tsx#L188

**Expected behavior**
The response object should either be passed into setState, or removed from the render prop.

**Comment by TejasQ** [comment]
Thanks for the find! Seems like a trivial fix! Wanna submit a PR? I’d be happy to merge!

**Comment by Xiot** [comment]
I tried putting it in locally and my unit tests kept freezing up. I haven't set up a react page yet to test it out for real. 
Also setState isn't 'await'able

**Comment by TejasQ** [comment]
Actually I’m pretty sure [`setState` is asynchronous](https://medium.com/@wereHamster/beware-react-setstate-is-asynchronous-ce87ef1a9cf3).

**Comment by TejasQ** [comment]
Right! My bad. Good catch!

**Comment by TejasQ** [comment]
Fixed in #7
