### ISSUE TITLE
Export simple type annotations for function-as-a-child arguments

### ISSUE THREAD

**Issue by peterszerzo** [contiamo/restful-react#69]
**Is your feature request related to a problem? Please describe.**
Sometimes it is necessary to pass down methods such as `refetch` and `mutate` that come from the function-as-a-child arguments of the `Get` and `Mutate` components, e.g. child component or a component method at which point they need a type annotation. Currently, this is quite hard to reproduce with the mutate API looking something like this: https://github.com/contiamo/restful-react/blob/master/src/Mutate.tsx#L119.

**Describe the solution you'd like**
The library should export interfaces for these methods taking the number and configuration of generics as the `Get` or `Mutate` components themselves. This would make type annotations straightforward and easy to follow.

**Comment by TejasQ** [comment]
Does the self-assignment mean you're making a PR that fixes this? 😄

**Comment by peterszerzo** [comment]
Yes, I got started on it - it turns out it is not that simple because `Mutate` works off of a union of different props configurations, so the type annotation of the method itself cannot be determined at compile-time. We can bypass this by exporting type annotations for all cases, and doing a manual type annotation in client code where the intent is known. How does that sound to you?

**Comment by TejasQ** [comment]
🤔 

> Mutate works off of a union of different props configurations, so the type annotation of the method itself cannot be determined at compile-time

I'm having a little trouble grokking this. Sorry, my head was just knee-deep in IdP talk. 😅 I might come back to this later. _Or_ if you could possible rephrase/illustrate with snippets I'd be grateful.

**Comment by peterszerzo** [comment]
The `mutate` argument in the render props pattern can have the following signatures:

`mutate: (body?: string | {}) => Promise<TData>`

`mutate: (resourceId?: string | {}) => Promise<TData>`

and this is based on whether we are working with `MutateWithDeleteProps` and `MutateWithOtherVerbProps`, but we won't be able to tell statically which one. Therefor my suggestion was to export both annotations and leave it up to the user to use the one that's relevant to each use-case when this comes up.

**Comment by peterszerzo** [comment]
Oh wow they're actually the same, never mind I didn't say anything :)
