### ISSUE TITLE
Independent requests

### ISSUE THREAD

**Issue by peterszerzo** [contiamo/restful-react#77]
**Is your feature request related to a problem? Please describe.**
Sometimes there is a need to fetch data and handle the response completely independently so that the state of `Get` and `Mutate` components is not affected at all, for instance in a Redux side effect manager. Request options, common headers, resolvers etc. should be the same for predictable usage.

**Describe the solution you'd like**
Expose an independent fetch method like so:
```js
<Get path="/dogs" lazy>
  {(_unusedDogs, _unusedStatus, { fetchIndependent }) => (
    <button onClick={() => fetchIndependent().then(() => {
      this.setState(/** */)
    })} />
  )}
</Get>
```

We can think of `fetchIndependent` as a version of e.g. `refetch` that doesn't change the state, so `_unusedDogs` and `_unusedStatus` will never change throughout the lifecycle of the component. I am using `lazy` in the example to indicate that not even an initial fetch needs to happen in this case, but the two different ways of using `restful-react` can be used in combination so that the app both relies on fetching an initial value, but then also passes the independent fetcher down someplace else (e.g. an epic middleware) without having to worry about unintended refetches happening somewhere up the component tree.

**Comment by TejasQ** [comment]
I really like this and I think it's a great idea. I don't see any immediate significant costs to adding this to the API, while I _do_ see some potential value adds we can have. For this reason, I'd say let's do it!

**Comment by TejasQ** [comment]
An entire year later, and the use case for this hasn't emerged while we're building the product, so I'm going to shelf this for now. Let's reopen the issue when this need becomes more apparent.
