### ISSUE TITLE
Do not stop polling after a failed poll request 

### ISSUE THREAD

**Issue by micha-f** [contiamo/restful-react#82]
**Describe the bug**
I left my browser open for a while and lost my internet connection for a few mins. `Poll` got a failed request and never made another poll request.

**To Reproduce**
1. Poll
2. Disable network, wait until request fails
3. Enable network again
4. No more polling requests

**Expected behavior**
We should think about a retry / backoff strategy for Polling

**Comment by TejasQ** [comment]
Thanks!

**Comment by TejasQ** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Don't stop polling on network error](https://trello.com/c/HAsTehBi/548-dont-stop-polling-on-network-error)

**Comment by TejasQ** [comment]
@fabien0102 I thought [this test](https://github.com/contiamo/restful-react/blob/master/src/Poll.test.tsx#L248-L286) covers this case well? I'm a little surprised we have this issue...

**Comment by TejasQ** [comment]
@micha-f, this issue conflicts with [the specification](https://www.notion.so/contiamo/Event-Streaming-Long-Polling-78c1905334314b32beff25c412a07281#4747e35f948e4846beb1e6c9ea298b4a), which suggests we do not continue polling after a failed request.

**Comment by TejasQ** [comment]
We don't need this anymore.
