### ISSUE TITLE
Implement a backoff strategy on Poll

### ISSUE THREAD

**Issue by TejasQ** [contiamo/restful-react#91]
**Is your feature request related to a problem? Please describe.**
This is related to #82. That issue is a little more nuanced as some error codes are retry-able, and others arent: for example, we can safely stop on a `404` and a `401`, but maybe not so much on a `503`.

Currently, if we're polling an endpoint that is returning retry-able error codes, it would be nice to have some type of backoff strategy.

**Describe the solution you'd like**

- Endpoint returns `503` (Temporarily Unavailalble)
  - We wait a little bit longer, try again
    - Still `503`
      - We wait _even longer_, try again
        - ...
          - `304`.
            - Awesome. Keep going.
              - `200` with `x-polling-index` header.
                - Awesome. Keep going.
                  - `200` without `x-polling-index` header
                      - Awesome. Stop.

**Describe alternatives you've considered**
1. Fail and stop polling until full reload: this doesn't quite make sense on things that are _retry-able_ (a la network downtime) because if the network comes back, the user needs to be updated.

1. Brute force poll: this will keep making requests against the server without letting it breathe and might be an exercise in futility since a server could be `503`ing for hours.

Thoughts?

**Comment by fabien0102** [comment]
Another idea, if it's only to deal with network downtime issue, we can implement this properly regarding the browser events (https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/Online_and_offline_events)

We can also add `retry` callback with a boolean to know that we are in this non-polling state, so we can add a nice modal/message to permit a retry from the user directly

**Comment by TejasQ** [comment]
Great idea! I think it's also more about the issue of kubernetes being "temporarily available" though.

**Comment by TejasQ** [comment]
We don't really need this anymore.
